apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-server
  namespace: devops
  labels:
    app: loki-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 20Gi
