apiVersion: v1
kind: Service
metadata:
  labels:
    app: loki-server
  name: loki-server
  namespace: devops
spec:
  ports:
  - name: http
    port: 3100
    protocol: TCP
    targetPort: 3100
  - name: metrics
    port: 3100
    protocol: TCP
    targetPort: 3100
  selector:
    app: loki-server
  type: ClusterIP
